# Generated by Django 2.2.7 on 2019-11-10 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=220)),
                ('dni', models.CharField(max_length=8)),
                ('avatar', models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/actor')),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=220)),
                ('dni', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('inicio', models.CharField(max_length=30)),
                ('fin', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('trailer', models.CharField(max_length=220)),
                ('duracion', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/pelicula')),
                ('idioma', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha Creación')),
                ('actor', models.ManyToManyField(to='cine.Actor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Categoria')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Genero')),
            ],
            options={
                'verbose_name': 'Pelicula',
                'verbose_name_plural': 'Peliculas',
                'ordering': ['titulo'],
            },
        ),
        migrations.AlterField(
            model_name='local',
            name='distrito_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Distrito'),
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('capacidad', models.IntegerField()),
                ('horario_id', models.ManyToManyField(to='cine.Horario')),
                ('local_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Local')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha Creación')),
                ('cantidad', models.IntegerField()),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha Creación')),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Cliente')),
                ('pelicula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Pelicula')),
                ('sala_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Sala')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['id'],
            },
        ),
    ]
